version: "3.8"

services:

  minio:
    image: quay.io/minio/minio
    container_name: minio

    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command:
      server /data --console-address ":9001"


  dbt:
    build:
      context: .
      dockerfile: docker/dbt/Dockerfile
    depends_on:
      - minio


  streamlit:
    build:
      context: .
      dockerfile: docker/streamlit/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - minio


volumes:
  minio_data: