---
title: "realtor_census_analysis.rmd"
output: html_document
author: "Miguel Rondon"
date: "2022-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rgdal)
```


```{r load analytical file}

rcdf <- read.csv("analytical_files/realtor_census.csv") %>% 
  select(2,19, 18, 5:17, 23:32)

``` 

``` {r next}
rcdf2 <- rcdf %>% 
  mutate(total_pop = total,
         total_pop_one_race_perc = total_population_of_one_race / total_pop,
         total_pop_white_perc = total_population_of_one_race_white_alone / total_pop,
         total_pop_black_perc = total_population_of_one_race_black_or_african_american_alone / total_pop,
         total_pop_american_indigenous_perc = total_population_of_one_race_american_indian_and_alaska_native_ / total_pop,
         total_pop_asian_perc = total_population_of_one_race_asian_alone / total_pop, 
total_pop_pacific_islander_perc = 
  total_population_of_one_race_native_hawaiian_and_other_pacific_ / total_pop,
         total_pop_other_perc = total_population_of_one_race_some_other_race_alone / total_pop, 
         total_pop_mixed_races_perc = total_population_of_two_or_more_races / total_pop,
         total_pop_hispanic_perc = total_hispanic_or_latino / total_pop,
         county_pop_size = case_when(total_pop < 50000 ~ "Non Metropolitan",
                                     total_pop < 250000 ~ "Small Metropolitan",
                                     total_pop < 1000000 ~ "Mid Metropolitan", 
                                     total_pop >= 1000000 ~ "Large Metropolitan"
                                     ),
         majority_hisp_or_race = case_when(total_pop_hispanic_perc > .5 ~ "Majority Hispanic",
                                   total_pop_white_perc > .5 ~ "Majority White",
                                   total_pop_black_perc > .5 ~ "Majority Black",
                                   total_pop_american_indigenous_perc > .5 ~ "Majority Native American", 
                                   total_pop_asian_perc > .5 ~ "Majority Asian", 
                                   total_pop_pacific_islander_perc > .5 ~ "Majority Pacific Islander", 
                                   total_pop_other_perc > .5 ~ "Majority Other Race", 
                                   total_pop_mixed_races_perc > .5~ "Majority Mixed Races", 
                                   TRUE ~ "No Majority Race"
                                   )
         ) %>% 
  filter(#new_listing_count > 0,
         #majority_hisp_or_race == "Majority Native American"
         #median_listing_price < 1000000, 
         #majority_hisp_or_race != "Majority White"
         #majority_hisp_or_race != "No Majority Race", 
         #county_pop_size != "Non Metropolitan",
         #county_pop_size == "Large Metropolitan"
         #majority_hisp_or_race == "Majority Black"
    )
  #filter(county_pop_size != 'Non Metropolitan', majority_hisp_or_race == "Majority Hispanic")
  
  #filter(total_pop_hispanic_perc > .5)#, median_listing_price < 750000)#, county_pop_size != 'Non Metropolitan')

rcdf2
```

```{r plot} 
ggplot(rcdf2, aes(median_listing_price / 1000, median_square_feet,
                   label = county)) + geom_point() +
  geom_text(vjust = -.5, size = 2.5)+ scale_x_log10() + scale_y_log10() + 
  geom_smooth(method = 'lm', se= FALSE)

cor(rcdf2$median_listing_price, rcdf2$median_square_feet, use= 'pairwise.complete.obs')

model <- lm(median_square_feet~median_listing_price, data=rcdf2)
model


``` 



```{r shapefile}
ggplot(rcdf2, aes(total_pop/ 1000, median_listing_price / 1000)) + 
  geom_point() + scale_x_log10() + scale_y_log10() + geom_smooth(method = 'lm', se= FALSE)

cor(rcdf2$median_listing_price, rcdf2$total_pop, use= 'pairwise.complete.obs')

model <- lm(median_listing_price~total_pop, data=rcdf2)
model


```

```{r categorical}
ggplot(rcdf2, aes(median_listing_price / 1000)) + geom_histogram() + facet_wrap(vars(majority_hisp_or_race))
```


```{r grid}
ggplot(rcdf2, aes(median_listing_price / 1000, total_pop)) + geom_point() +
         facet_grid(align ~ majority_hisp_or_race)
```

